# Generated by Django 2.0.13 on 2019-03-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('rate', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='currencies.History'),
        ),
    ]
